audit_header: false
title: Colorado Springs Real Estate Video Blog with Jason Daniels
description: >-
  Our mission at Finch & Gable is to be your best resource for Colorado Springs
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The Finch & Gable, your professional
  Colorado Springs Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Testimonials
    url: '#testimonials'
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Jason Daniels
  title:
  license_number:
  about_markdown: >-
    Jason is a Colorado native and has lived in Colorado Springs for over 30
    years. Jason and his team have sold twelve hundred homes over the past 16
    years in Colorado Springs. He enjoys all types of outdoor activities
    including hiking, biking, camping, skiing, and golfing. Jason graduated from
    Colorado State University with a bachelor’s degree in Construction
    Management. He is married with six children and enjoys spending time with
    family. Jason and his team specialize with first time buyers, investors,
    golf course properties, luxury homes, military relocation, and new home
    construction. He is also a member of Peak Producers and the Elite 25, both
    exclusive groups of top agents in the Colorado Springs area.
  market: Colorado Springs
  brand: Finch & Gable Real Estate Co.
  brokerage:
  address: '9362 Grand Cordera Pkwy #100<br>Colorado Springs, CO 80924'
  phone: 719-999-8900
  phone_type:
  phone2:
  phone2_type:
  email: info@jasondanielshomes.com
  url: 'http://www.jasondanielshomes.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.coloradohomesvalue.com/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.coloradospringstophomes.com/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Colorado Springs Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'http://www.coloradohomesvalue.com/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Colorado Springs Home?
    CTA_text2: Search the entire MLS for your Colorado Springs home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'http://www.coloradospringstophomes.com/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Colorado Springs Real Estate Podcast with Jason Daniels
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Colorado
    Springs Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Finch & Gable - your professional
    Colorado Springs Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Colorado
    Springs, home selling tips, home for sale, home buying, home buying process,
    property finder, property search, property, real estate market, estate
    agent, realestate, real estate listings, buying a house, homes for sale,
    mls, home buyer
  author: Jason Daniels
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Colorado Springs Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#fc6669'
  accent_color: '#96694c'
  theme_color: '#33312d'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#96694c'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'